version: 3.8
services:
  jobmanager-a:
    container_name: jobmanager-a
    platform: linux/arm64/v8
    build:
      context: ./images/pyflink
      dockerfile: .Dockerfile
    ports:
      - "8041:8041"
    command: jobmanager
    attach: false
    restart: always
    volumes:
      - ./datasets:/opt/flink/datasets
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        jobmanager.memory.process.size: 2000m
        jobmanager.rest.port: 8041
  taskmanager-a:
    container_name: taskmanager-a
    platform: linux/arm64/v8
    attach: false
    restart: always
    build:
      context: ./images/pyflink
      dockerfile: .Dockerfile
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - ./datasets:/opt/flink/datasets
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
        parallelism.default: 1
        taskmanager.memory.process.size: 2500m
        taskmanager.memory.framework.off-heap.size: 500m
        taskmanager.memory.task.off-heap.size: 1000m
        taskmanager.memory.jvm-metaspace.size: 3000m
    
