version: "3"
services:
  pyflink-client:
    platform: linux/amd64
    container_name: pyflink-client
    image: barsnir/pyflink:v1
    command: sleep 5000
    environment:
      - DATABASE=production
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=password
      - ENV=development
      - DB_CONFIG=/opt/flink/project/configs/database.json
      - SCRIPTS_PATH_DIR=/opt/flink/project/scripts
    volumes:
      - ./flink_process:/opt/flink/ops
      - ./jars:/opt/flink/opt
      - ./datasets:/opt/flink/datasets
      - .:/opt/flink/project
      - /var/run/docker.sock:/var/run/docker.sock