services:
  jobmanager:
    container_name: jobmanager
    platform: linux/arm64/v8
    build:
      context: ./images/pyflink
      dockerfile: .Dockerfile
    ports:
      - "8081:8081"
    command: jobmanager
    attach: false
    volumes:
      - ./datasets:/opt/flink/datasets
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        jobmanager.memory.process.size: 4096m
  taskmanager:
    container_name: taskmanager
    platform: linux/arm64/v8
    build:
      context: ./images/pyflink
      dockerfile: .Dockerfile
    depends_on:
      - jobmanager
    command: taskmanager
    attach: false
    volumes:
      - ./datasets:/opt/flink/datasets
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 32
        parallelism.default: 4
        taskmanager.memory.process.size: 4096m
    links:
      - db:db
  taskmanager2:
    container_name: taskmanager2
    platform: linux/arm64/v8
    build:
      context: ./images/pyflink
      dockerfile: .Dockerfile
    depends_on:
      - jobmanager
    command: taskmanager
    attach: false
    volumes:
      - ./datasets:/opt/flink/datasets
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 32
        parallelism.default: 4
        taskmanager.memory.process.size: 4096m
    links:
      - db:db
  pyflink-client:
    platform: linux/arm64/v8
    container_name: pyflink-client
    build:
      context: ./images/pyflink
      dockerfile: .Dockerfile
    depends_on:
      - jobmanager
      - taskmanager
    command: >
      bash -c  "echo 'starting flink cluster in 30s' && sleep 30 && ./bin/flink run \
      --jobmanager jobmanager:8081 \
      -pyclientexec /usr/local/bin/python3 \
      -pyexec /usr/local/bin/python3 \
      -py /opt/flink/ops/generate_market_info.py"
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 4
    volumes:
      - ./flink_process:/opt/flink/ops
      - ./jars:/opt/flink/opt
    scale: 1
  db:
    container_name: legacy-mysql
    image: mysql:5.7
    platform: linux/x86_64
    restart: always
    attach: false
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: