services:
  jobmanager:
    container_name: jobmanager
    platform: linux/arm64/v8
    build:
      context: ./images/pyflink
      dockerfile: .Dockerfile
    ports:
      - "8081:8081"
    command: jobmanager
    attach: false
    volumes:
      - ./datasets:/opt/flink/datasets
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        jobmanager.memory.process.size: 2000m
  taskmanager:
    container_name: taskmanager
    platform: linux/arm64/v8
    attach: false
    build:
      context: ./images/pyflink
      dockerfile: .Dockerfile
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - ./datasets:/opt/flink/datasets
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 16
        parallelism.default: 8
        taskmanager.memory.process.size: 7500m
        taskmanager.memory.framework.off-heap.size: 500m
        taskmanager.memory.task.off-heap.size: 1000m
        taskmanager.memory.jvm-metaspace.size: 600m
    links:
      - db:db
  pyflink-client:
    platform: linux/arm64/v8
    container_name: pyflink-client
    build:
      context: ./images/pyflink
      dockerfile: .Dockerfile
    depends_on:
      - jobmanager
      - taskmanager
    command: >
      bash -c  "chmod +x ./project && \
      ./project/scripts/database_setup.sh"
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        parallelism.default: 4
      - DATABASE=production
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - ENV=development
      - DB_CONFIG=/opt/flink/project/configs/database.json
    volumes:
      - ./flink_process:/opt/flink/ops
      - ./jars:/opt/flink/opt
      - ./datasets:/opt/flink/datasets
      - .:/opt/flink/project
    scale: 1
  db:
    container_name: legacy-mysql
    image: mysql:5.7
    platform: linux/x86_64
    restart: always
    attach: false
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: