maps_helper = {
    'gemetria': {
        'a': 1,
        'b': 2,
        'c': 3,
        'd': 4,
        'e': 5,
        'f': 6,
        'g': 7,
        'h': 8,
        'i': 9,
        'j': 10,
        'k': 20,
        'l': 30,
        'm': 40,
        'n': 50,
        'o': 60,
        'p': 70,
        'q': 80,
        'r': 90,
        's': 100,
        't': 200, 
        'u': 300, 
        'v': 400, 
        'w': 500, 
        'x': 600, 
        'y': 700, 
        'z': 800
    },
    'market_info_year': {
        'Year_Sunroof': 2008,
        'Year_MagnesiumWheels': 2005,
        'Year_ReversSensors': 2002,
        'Year_Hybrid': 2012,
        'Year_CruseControl': 2005,
        'Year_PowerWheel': 1999,
        'Year_FullyAutonomic': 2021
    },
    'market_info_ranges':{
        'airbags': {'low': 0, 'high': 5},
        'doors': {'low': 2, 'high': 5},
        'environment_friendly_level': {'low': 0, 'high': 11},
        'security_test_level': {'low': 0, 'high': 11},
        'horse_power': {'low': 8*10, 'high': 45*10},
        'market_price': {'low': 1000*10, 'high': 45000*10},
        'family_type': {'low': 1, 'high': 6},
    },
    'vehicles_ranges':{
        'km': {'low': 1000*10, 'high': 45000*10},
        'prev_owner_number': {'low':0, 'high': 7},
        'media_type_id': {'low': 1, 'high': 11},
        'improve_id': {'low': 1, 'high': 11},
    },
    'order_ranges': {
        'price': {'low': 1000*10, 'high': 45000*10},
        'status_id': {'low': 1, 'high': 11},
        'customer_id': {'low': 1, 'high': 8000},
    },
    "customer_ranges":{
        'customer_type_id': {'low': 1, 'high': 6},
        'is_suspended': {'low': 0, 'high': 2},
        'suspended_reason_id': {'low': 1, 'high': 7},
        'auth_type_id': {'low': 1, 'high': 5},
    },
    "improves": {
        1: ['media'],
        2: ['media', 'speaker'],
        3: ['media', 'speaker', 'fuel-system'],
        4: ['media', 'speaker', 'fuel-system', 'back-seats-media'],
        5: ['media', 'speaker', 'fuel-system', 'back-seats-media', 'shaded-windows'],
        6: ['media', 'speaker', 'fuel-system', 'back-seats-media', 'shaded-windows', 'engine-cooler'],
        7: ['media', 'speaker', 'fuel-system', 'back-seats-media', 'shaded-windows', 'engine-cooler', 'engine-fan'],
        8: ['media', 'speaker', 'fuel-system', 'back-seats-media', 'shaded-windows', 'engine-cooler', 'engine-fan', 'stage-1'],
        9: ['media', 'speaker', 'fuel-system', 'back-seats-media', 'shaded-windows', 'engine-cooler', 'engine-fan', 'stage-1', 'stage-2'],
        10: ['media', 'speaker', 'fuel-system', 'back-seats-media', 'shaded-windows', 'engine-cooler', 'engine-fan', 'stage-1', 'stage-2', 'stage-3'],
    },
    "improves_stage_level": {
        8: 'SOFTWARE',
        9: 'SOFTWARE+ENGINE',
        10: 'SOFTWARE+ENGINE+SHIELD',
    },
    "suspended_dict":{
        '1': 'impostor',
        '2': 'payment',
        '3': 'hacker',
        '4': 'scam',
        '5': 'bot',
        '6': 'spam',
    },
    "customer_type_dict": {
        '1': 'regular',
        '2': 'bronze',
        '3': 'silver',
        '4': 'gold',
        '5': 'platinum'
    },
    "status_text":{
        '1': 'activate',
        '2': 'waiting_for_cms_approve',
        '3': 'waiting_for_payment_approve',
        '4': 'freeze',
        '5': 'sold',
        '6': 'in_publish_queue',
        '7': 'deactivate'
    },
    "family_type_text":{
        '1': 'mini',
        '2': 'private',
        '3': 'family',
        '4': 'crossover',
        '5': 'luxury',
        '6': 'sport'
    }
}