maps_helper = {
    'gemetria': {
        'a': 1,
        'b': 2,
        'c': 3,
        'd': 4,
        'e': 5,
        'f': 6,
        'g': 7,
        'h': 8,
        'i': 9,
        'j': 10,
        'k': 20,
        'l': 30,
        'm': 40,
        'n': 50,
        'o': 60,
        'p': 70,
        'q': 80,
        'r': 90,
        's': 100,
        't': 200, 
        'u': 300, 
        'v': 400, 
        'w': 500, 
        'x': 600, 
        'y': 700, 
        'z': 800
    },
    'market_info_year': {
        'Year_Sunroof': 2008,
        'Year_MagnesiumWheels': 2005,
        'Year_ReversSensors': 2002,
        'Year_Hybrid': 2012,
        'Year_CruseControl': 2005,
        'Year_PowerWheel': 1999,
        'Year_FullyAutonomic': 2021
    },
    'market_info_ranges':{
        'airbags': {'low': 0, 'high': 5},
        'doors': {'low': 2, 'high': 5},
        'environment_friendly_level': {'low': 0, 'high': 11},
        'security_test_level': {'low': 0, 'high': 11},
        'horse_power': {'low': 8*10, 'high': 45*10},
        'market_price': {'low': 1000*10, 'high': 45000*10},
    },
    'vehicles_ranges':{
        'km': {'low': 1000*10, 'high': 45000*10},
        'prev_owner_number': {'low':0, 'high': 7},
        'media_type_id': {'low': 1, 'high': 11},
        'improve_id': {'low': 1, 'high': 11},
    }
}