version: "3"
services:
  flink-batch-jobmanager:
    platform: linux/amd64
    container_name: flink-batch-jobmanager
    image: barsnir/pyflink:v1
    ports:
      - "4040:4040"
    command: jobmanager
    attach: false
    restart: always
    volumes:
      - ../datasets:/opt/flink/datasets
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.memory.process.size: 1000m
        jobmanager.rpc.address: flink-batch-jobmanager
        rest.port: 4040
        rest.bind-port: 4030-4050
    networks:
      - compose_ingest-network
      - default
  flink-batch-taskmanager:
    platform: linux/amd64
    container_name: flink-batch-taskmanager
    image: barsnir/pyflink:v1
    attach: false
    restart: always
    command: taskmanager
    volumes:
      - ../datasets:/opt/flink/datasets
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-batch-jobmanager
        taskmanager.numberOfTaskSlots: 5
        parallelism.default: 1
        taskmanager.memory.process.size: 6000m
        taskmanager.memory.jvm-metaspace.size: 1000m
        taskmanager.memory.managed.size: 100m
        restart-strategy.type: fixed-delay
        restart-strategy.fixed-delay.attempts: 3
        restart-strategy.fixed-delay.delay: 3 m
    networks:
      - compose_ingest-network
      - default
  pyflink-client:
    platform: linux/amd64
    container_name: pyflink-client
    image: barsnir/pyflink:v1
    command: bash ./project/scripts/steps.sh
    environment:
      - DATABASE=production
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - ENV=development
      - DB_CONFIG=/opt/flink/project/configs/database.json
      - SCRIPTS_PATH_DIR=/opt/flink/project/scripts
      - FLINK_BATCH_CLUSTER_HOST=flink-batch-jobmanager
      - FLINK_BATCH_CLUSTER_PORT=4040
    volumes:
      - ../flink_process:/opt/flink/ops
      - ../jars:/opt/flink/opt
      - ../datasets:/opt/flink/datasets
      - ..:/opt/flink/project
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - compose_ingest-network
      - default
    external_links:
      - legacy-mysql:db
networks:
  compose_ingest-network:
    external: true
  default:
    driver: bridge